#########################################################################
# Copyright (C) 2021 Akito <the@akito.ooo>                              #
#                                                                       #
# This program is free software: you can redistribute it and/or modify  #
# it under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or     #
# (at your option) any later version.                                   #
#                                                                       #
# This program is distributed in the hope that it will be useful,       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          #
# GNU General Public License for more details.                          #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see <http://www.gnu.org/licenses/>. #
#########################################################################

version: '3.3'

services:
  rclone:
    image: rclone/rclone
    container_name: rclone
    user: 755:754 # Must be the same as the uid:gid of the actual OS user outside of Docker.
    entrypoint: ["/bin/sh", "-c", "/data/entrypoint.sh"]
    devices:
      # By default, the container will be able to read, write, and mknod these devices.
      # This can be overridden using a third :rwm set of options to each --device flag.
      - '/dev/fuse:/dev/fuse:rwm'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    environment:
      - 'RCLONE_WEBDAV_USER=<your-icedrive-login>'
      # Do not provide a password here, but use `prep-pw.sh` as described in the instructions.
    volumes:
      # Change mountpoint (left part) to your needs.
      - '/home/rclone/data:/data:shared'
      - '/home/rclone/config:/config/rclone'
      # Do not modify the following.
      - '/etc/passwd:/etc/passwd:ro'
      - '/etc/group:/etc/group:ro'